<?php

declare(strict_types=1);

namespace BeeperDesktop\Matrix\Rooms\Events\EventGetResponse;

use BeeperDesktop\Core\Attributes\Optional;
use BeeperDesktop\Core\Concerns\SdkModel;
use BeeperDesktop\Core\Contracts\BaseModel;

/**
 * @phpstan-type UnsignedShape = array{
 *   age?: int|null,
 *   membership?: string|null,
 *   prevContent?: mixed,
 *   redactedBecause?: mixed,
 *   transactionID?: string|null,
 * }
 */
final class Unsigned implements BaseModel
{
    /** @use SdkModel<UnsignedShape> */
    use SdkModel;

    /**
     * The time in milliseconds that has elapsed since the event was sent. This field is generated by the local homeserver, and may be incorrect if the local time on at least one of the two servers is out of sync, which can cause the age to either be negative or greater than it actually is.
     */
    #[Optional]
    public ?int $age;

    /**
     * The room membership of the user making the request, at the time of the event.
     *
     * This property is the value of the `membership` property of the
     * requesting user's [`m.room.member`](https://spec.matrix.org/v1.18/client-server-api#mroommember)
     * state at the point of the event, including any changes caused by the
     * event. If the user had yet to join the room at the time of the event
     * (i.e, they have no `m.room.member` state), this property is set to
     * `leave`.
     *
     * Homeservers SHOULD populate this property
     * wherever practical, but they MAY omit it if necessary (for example,
     * if calculating the value is expensive, servers might choose to only
     * implement it in encrypted rooms). The property is *not* normally populated
     * in events pushed to application services via the application service transaction API
     * (where there is no clear definition of "requesting user").
     */
    #[Optional]
    public ?string $membership;

    /**
     * The previous `content` for this event. This field is generated
     * by the local homeserver, and is only returned if the event is a state event,
     * and the client has permission to see the previous content.
     */
    #[Optional('prev_content')]
    public mixed $prevContent;

    #[Optional('redacted_because')]
    public mixed $redactedBecause;

    /**
     * The client-supplied [transaction ID](https://spec.matrix.org/v1.18/client-server-api/#transaction-identifiers), for example, provided via
     * `PUT /_matrix/client/v3/rooms/{roomId}/send/{eventType}/{txnId}`,
     * if the client being given the event is the same one which sent it.
     */
    #[Optional('transaction_id')]
    public ?string $transactionID;

    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(
        ?int $age = null,
        ?string $membership = null,
        mixed $prevContent = null,
        mixed $redactedBecause = null,
        ?string $transactionID = null,
    ): self {
        $self = new self;

        null !== $age && $self['age'] = $age;
        null !== $membership && $self['membership'] = $membership;
        null !== $prevContent && $self['prevContent'] = $prevContent;
        null !== $redactedBecause && $self['redactedBecause'] = $redactedBecause;
        null !== $transactionID && $self['transactionID'] = $transactionID;

        return $self;
    }

    /**
     * The time in milliseconds that has elapsed since the event was sent. This field is generated by the local homeserver, and may be incorrect if the local time on at least one of the two servers is out of sync, which can cause the age to either be negative or greater than it actually is.
     */
    public function withAge(int $age): self
    {
        $self = clone $this;
        $self['age'] = $age;

        return $self;
    }

    /**
     * The room membership of the user making the request, at the time of the event.
     *
     * This property is the value of the `membership` property of the
     * requesting user's [`m.room.member`](https://spec.matrix.org/v1.18/client-server-api#mroommember)
     * state at the point of the event, including any changes caused by the
     * event. If the user had yet to join the room at the time of the event
     * (i.e, they have no `m.room.member` state), this property is set to
     * `leave`.
     *
     * Homeservers SHOULD populate this property
     * wherever practical, but they MAY omit it if necessary (for example,
     * if calculating the value is expensive, servers might choose to only
     * implement it in encrypted rooms). The property is *not* normally populated
     * in events pushed to application services via the application service transaction API
     * (where there is no clear definition of "requesting user").
     */
    public function withMembership(string $membership): self
    {
        $self = clone $this;
        $self['membership'] = $membership;

        return $self;
    }

    /**
     * The previous `content` for this event. This field is generated
     * by the local homeserver, and is only returned if the event is a state event,
     * and the client has permission to see the previous content.
     */
    public function withPrevContent(mixed $prevContent): self
    {
        $self = clone $this;
        $self['prevContent'] = $prevContent;

        return $self;
    }

    public function withRedactedBecause(mixed $redactedBecause): self
    {
        $self = clone $this;
        $self['redactedBecause'] = $redactedBecause;

        return $self;
    }

    /**
     * The client-supplied [transaction ID](https://spec.matrix.org/v1.18/client-server-api/#transaction-identifiers), for example, provided via
     * `PUT /_matrix/client/v3/rooms/{roomId}/send/{eventType}/{txnId}`,
     * if the client being given the event is the same one which sent it.
     */
    public function withTransactionID(string $transactionID): self
    {
        $self = clone $this;
        $self['transactionID'] = $transactionID;

        return $self;
    }
}
